#Requires -Version 5.1
# Export-TridentReport — runs Detect (no installs, no downloads) and writes a
# markdown report for bug posts / coordination. NEW additive file, safe lane.
# Run: powershell -NoProfile -ExecutionPolicy Bypass -File tools\Export-Report.ps1
Set-StrictMode -Version Latest
$ErrorActionPreference = 'Stop'
$here = Split-Path $MyInvocation.MyCommand.Path -Parent
$src = Join-Path (Split-Path $here -Parent) 'src'
. (Join-Path $src 'Trident.Core.ps1')
. (Join-Path $src 'Trident.Core.Part2.ps1')
. (Join-Path $src 'Trident.Core.Part3.ps1')

$stamp = Get-Date -Format 'yyyyMMdd-HHmmss'
$reports = Join-Path $env:TEMP 'trident'
if (-not (Test-Path $reports)) { New-Item -ItemType Directory -Force -Path $reports | Out-Null }
$outFile = Join-Path $reports ('trident-report-' + $stamp + '.md')

$arch = Get-TridentArch -Wanted 'auto'
$lines = @()
$lines += '# Trident detect report'
$lines += ''
$lines += ('- Date: ' + (Get-Date -Format 'yyyy-MM-dd HH:mm:ss'))
$lines += ('- Core: ' + $script:TridentVersion)
$lines += ('- Arch: ' + $arch)
$lines += ('- OS: ' + [Environment]::OSVersion.VersionString)
$lines += ''
$lines += '| Package | Flag | Status | Detail |'
$lines += '|---|---|---|---|'
foreach ($p in $script:Catalog) {
  $d = Detect-TridentPackage -Pkg $p
  $safe = ([string]$d.Detail).Replace('|', '/')
  $lines += ('| ' + $p.Name + ' | ' + $p.Flag + ' | ' + $d.Status + ' | ' + $safe + ' |')
}
$lines += ''
$lines += 'Generated by tools/Export-Report.ps1 (detect only, no changes).'
$lines | Set-Content -Path $outFile -Encoding UTF8
Write-Output $outFile
